# Generated by Django 5.0.6 on 2025-11-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='nok_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Next of Kin Name'),
        ),
    ]
