# Generated by Django 4.2.24 on 2025-10-29 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_memberprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberprofile',
            old_name='address',
            new_name='nok_address',
        ),
        migrations.RenameField(
            model_name='memberprofile',
            old_name='next_of_kin',
            new_name='other_name',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='national_id',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='area_of_residence',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='given_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='nok_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='nok_date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='nok_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Next of Kin name'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='nok_relationship',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='parents_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='member_photos/'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='surname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='date_of_birth',
            field=models.DateField(null=True, blank=True),

        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
