# Generated by Django 4.2.24 on 2025-10-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_address_memberprofile_nok_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
