# Generated by Django 5.2.7 on 2025-11-15 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_memberprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memberprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
