# Generated by Django 5.0.6 on 2025-11-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Loan Payment', 'Loan Payment'), ('Loan Disbursement', 'Loan Disbursement')], max_length=50),
        ),
    ]
