# Generated by Django 5.0.6 on 2025-11-23 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        ('transactions', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrepayment',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction'),
        ),
    ]
